# 为什么使用 numpy 数组？
Numpy是你在学习无人驾驶汽车时不断出现的工具之一。 这是因为numpy数组往往：

1. **紧凑** （它们不占用Python列表的内存空间）。

2. **高效**（numpy数组的计算通常比Python列表计算快得多）。

3. **方便** （我们现在将更多地讨论这方面的话题）。

In [1]:
# consider this 2d python grid (list of lists)
grid = [
    [0, 1, 5],
    [1, 2, 6],
    [2, 3, 7],
    [3, 4, 8]
]

# It's easy to print, for example, row number 0:
print(grid[0])

[0, 1, 5]


In [2]:
# but how would you print COLUMN 0? In numpy, this is easy

import numpy as np

np_grid = np.array([
    [0, 1, 5],
    [1, 2, 6],
    [2, 3, 7],
    [3, 4, 8]
])

# The ':' usually means "*all values*
print(np_grid[:,0])

[0 1 2 3]


In [3]:
# What if you wanted to change the shape of the array?

# For example, we can turn the 2D grid from above into a 1D array
# Here, the -1 means automatically fit all values into this 1D shape
np_1D = np.reshape(np_grid, (1, -1))

print(np_1D)

[[0 1 5 1 2 6 2 3 7 3 4 8]]


In [3]:
# We can also create a 2D array of zeros or ones
# which is useful for car world creation and analysis

# Create a 5x4 array
zero_grid = np.zeros((5, 4))

print(zero_grid)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
